# fly.toml app configuration file generated for mern-invoice-summer-rain-105 on 2024-03-13T17:26:30+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mern-invoice-summer-rain-105'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
